starter_main/starter_main/urls.py
from django.contrib import admin
from django.urls import path
from boards import views

urlpatterns = [
    path(r'', views.home, name="home"),
    path(r'boards/<int:pk>', views.board_topics, name='board_topic'),
    path(r'boards/<int:pk>/new/', views.new_topic, name='new_topic'),
    path('admin/', admin.site.urls),    
]

starter_main/boards/models.py
from django.db import models
from django.contrib.auth.models import User

class Board(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
        

class Topic(models.Model):
    subject = models.CharField(max_length=200)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name="topics", on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name="topics",  on_delete=models.CASCADE)

    def __str__(self):
        return self.subject
    
    
class Post(models.Model):
    message = models.TextField(max_length=1000)
    topic = models.ForeignKey(Topic, related_name="posts",  on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name="posts",  on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null=True, related_name="+",  on_delete=models.CASCADE)
    
    def __str__(self):
        return self.message
    

starter_main/boards/forms.py
from django import forms
from .models import Topic

class NewTopicForm(forms.ModelForm):
    
    class Meta:
        model = Topic
        fields = ["subject", "message"]

starter_main/boards/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Board, Topic, Post
from django.contrib.auth.models import User
from django.http import Http404
from .forms import NewTopicForm

# Create your views here.


def home(request):
    boards = Board.objects.all()

    return render(request, 'boards/home.html', {'boards': boards})


def board_topics(request, pk):
    board = get_object_or_404(Board, pk=pk)
    return render(request, 'boards/topics.html', {'board': board})

def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    
    if request.method == 'POST':
        # subject = request.POST['subject']
        # message = request.POST['message']
        
        user = User.objects.first()
        
        form = NewTopicForm(request.POST)
        
        if form.is_valid():
        
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = user
            topic.save()
            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=user
            )
            return redirect('board_topics', pk=board.pk)  # TODO: redirect to the created topic page
    else:
        form = NewTopicForm()
    return render(request, 'new_topic.html', {'board': board, 'form': form})

starter_main/boards/templates/boards/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
        </div>
      </nav>

    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

starter_main/boards/templates/boards/home.html
{% extends 'boards/base.html' %}

{%block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{% endblock %}


{% block content  %}
    <table class="table">
    <thead class="thead-inverse">
        <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
        </tr>
    </thead>
    <tbody>
        {% for board in boards %}
        <tr>
            <td>
            <a href="{% url 'board_topic' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
            </td>
            <td class="align-middle">0</td>
            <td class="align-middle">0</td>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

{% endblock %}

starter_main/boards/templates/boards/new_topic.html
{% extends 'boards/base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topic' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <!-- <div class="form-group">
        <label for="id_subject">Subject</label>
        <input type="text" class="form-control" id="id_subject" name="subject">
      </div>
      <div class="form-group">
        <label for="id_message">Message</label>
        <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
      </div> -->
      <button type="submit" class="btn btn-success">Post</button>

</form>

{% endblock %}

starter_main/boards/templates/boards/topics.html
{% extends 'boards/base.html'%}

{% block title %}
{{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

  
{% block content %}
    <div class="mb-4">
        <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New topic</a>
    </div>
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>Topic</th>
                <th>Starter</th>
                <th>Replies</th>
                <th>Views</th>
                <th>Last Update</th>
            </tr>
        </thead>
        <tbody>
            {% for topic in board.topics.all %}
            <tr>
              <td>{{ topic.subject }}</td>
              <td>{{ topic.starter.username }}</td>
              <td>0</td>
              <td>0</td>
              <td>{{ topic.last_updated }}</td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
{% endblock %}